app/urls.py
from django.urls import path, include
from .views import home, contacto, galeria, agregar_deptos, listarDeptos, modificarDeptos, eliminarDptos,\
    registro, DepartamentoViewset, reserva
from rest_framework import routers


router = routers.DefaultRouter()
router.register('depa', DepartamentoViewset)


urlpatterns = [
    path('', home, name="home"),
    path('contacto/', contacto, name="contacto"),
    path('galeria/', galeria, name="galeria"),
    path('agregarDep/', agregar_deptos, name="agregarDep"),
    path('listarDep/', listarDeptos, name="listarDep"),
    path('modificarDep/<id_depa>/', modificarDeptos, name="modificarDep"),
    path('eliminarDep/<id_depa>/', eliminarDptos, name="eliminarDep"),
    path('registro/', registro, name="registro"),
    path('api/', include(router.urls)),
     path('reserva/', reserva, name="reserva"),

]

webarriendos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.db.models.base import Model
from django.utils.regex_helper import Choice


class Acompaniante(models.Model):
    id_acomp = models.FloatField(primary_key=True)
    cantidad = models.BigIntegerField()
    direccion = models.CharField(max_length=150)
    telefono = models.CharField(max_length=20)
    correo = models.CharField(max_length=150)
    estado = models.FloatField()

    class Meta:
        managed = False
        db_table = 'acompaniante'


class Administrador(models.Model):
    id_admi = models.FloatField(primary_key=True)
    estado = models.FloatField()
    id_usua = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usua')

    class Meta:
        managed = False
        db_table = 'administrador'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128, blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150, blank=True, null=True)
    first_name = models.CharField(max_length=150, blank=True, null=True)
    last_name = models.CharField(max_length=150, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Cargo(models.Model):
    id_carg = models.FloatField(primary_key=True)
    nombre = models.CharField(max_length=150)
    detalle_cargo = models.CharField(max_length=200)
    estado = models.FloatField()

    class Meta:
        managed = False
        db_table = 'cargo'


class CheckIn(models.Model):
    id_chin = models.FloatField(primary_key=True)
    detalle_entrega = models.CharField(max_length=150)
    pago_pendiente = models.CharField(max_length=150)
    ingreso_conformidad = models.CharField(max_length=150)
    hora_chin = models.DateTimeField()
    fecha_chin = models.DateField()
    estado = models.FloatField()
    id_func = models.ForeignKey('Funcionario', models.DO_NOTHING, db_column='id_func')
    id_rese = models.ForeignKey('Reserva', models.DO_NOTHING, db_column='id_rese')

    class Meta:
        managed = False
        db_table = 'check_in'


class CheckOut(models.Model):
    id_chou = models.FloatField(primary_key=True)
    estado_entrega = models.CharField(max_length=50)
    multas_out = models.CharField(max_length=50)
    pagos_multas_out = models.CharField(max_length=50)
    hora_chou = models.DateTimeField()
    fecha_chou = models.DateField()
    estado = models.FloatField()
    id_func = models.ForeignKey('Funcionario', models.DO_NOTHING, db_column='id_func')
    id_chin = models.ForeignKey(CheckIn, models.DO_NOTHING, db_column='id_chin')

    class Meta:
        managed = False
        db_table = 'check_out'


class Cliente(models.Model):
    id_clie = models.FloatField(primary_key=True)
    estado = models.FloatField()
    id_acomp = models.ForeignKey(Acompaniante, models.DO_NOTHING, db_column='id_acomp')
    id_usua = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usua')

    class Meta:
        managed = False
        db_table = 'cliente'



class Comuna(models.Model):
    id_comu = models.FloatField(primary_key=True)
    nombre = models.CharField(max_length=150)
    estado = models.FloatField()
    id_prov = models.ForeignKey('Provincia', models.DO_NOTHING, db_column='id_prov')

    class Meta:
        managed = False
        db_table = 'comuna'
    
    
    def __str__(self):
        return self.nombre

class Conductor(models.Model):
    id_cond = models.FloatField(primary_key=True)
    nombre = models.CharField(max_length=150)
    apellido = models.CharField(max_length=150)
    direccion = models.CharField(max_length=150)
    correo = models.CharField(max_length=150)
    estado = models.FloatField()

    class Meta:
        managed = False
        db_table = 'conductor'


class Departamento(models.Model):
    id_depa = models.FloatField(primary_key=True)
    nombre = models.CharField(max_length=150)
    info_departamento = models.CharField(max_length=150)
    servicio_asociado = models.CharField(max_length=150)
    entorno_departamento = models.CharField(max_length=150)
    tarifa = models.BigIntegerField()
    condicion_uso = models.CharField(max_length=150)
    estado = models.FloatField()
    id_admi = models.ForeignKey(Administrador, models.DO_NOTHING, db_column='id_admi')
    id_edificio = models.ForeignKey('Edificio', models.DO_NOTHING, db_column='id_edificio')
    

    class Meta:
        managed = False
        db_table = 'departamento'


class Direccion(models.Model):
    id_dire = models.FloatField(primary_key=True)
    nombre_calle = models.CharField(max_length=150)
    numero_calle = models.IntegerField()
    estado = models.FloatField()
    id_comu = models.ForeignKey(Comuna, models.DO_NOTHING, db_column='id_comu')

    class Meta:
        managed = False
        db_table = 'direccion'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200, blank=True, null=True)
    action_flag = models.IntegerField()
    change_message = models.TextField(blank=True, null=True)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100, blank=True, null=True)
    model = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField(blank=True, null=True)
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Edificio(models.Model):
    id_edificio = models.FloatField(primary_key=True)
    estado = models.FloatField()
    id_dire = models.ForeignKey(Direccion, models.DO_NOTHING, db_column='id_dire')

    class Meta:
        managed = False
        db_table = 'edificio'


class Funcionario(models.Model):
    id_func = models.FloatField(primary_key=True)
    estado = models.FloatField()
    id_carg = models.ForeignKey(Cargo, models.DO_NOTHING, db_column='id_carg')
    id_usua = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usua')

    class Meta:
        managed = False
        db_table = 'funcionario'


class InformeGanancia(models.Model):
    id_inga = models.FloatField(primary_key=True)
    ganancia_departamento = models.BigIntegerField()
    ganancia_zona = models.BigIntegerField()
    ganancia_diaria = models.BigIntegerField()
    ganancia_semanal = models.BigIntegerField()
    ganancia_anual = models.BigIntegerField()
    estado = models.FloatField()
    id_admi = models.ForeignKey(Administrador, models.DO_NOTHING, db_column='id_admi')

    class Meta:
        managed = False
        db_table = 'informe_ganancia'


class InformeReserva(models.Model):
    id_inre = models.FloatField(primary_key=True)
    detalle = models.CharField(max_length=150)
    estado = models.FloatField()

app/templates/deptos/agregar.html
{% extends 'app/base.html' %}

{% block contenido %}



<br><br>
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <h2>Agregar Departamentos</h2>
                        <hr>

                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Guardar" class="btn btn-primary">   

                    </div>
                  

                </form>
                {{ mensaje }}

            </div>
        </div>


    </div>
</div>


{% endblock %}

app/templates/deptos/listar.html
{% extends 'app/base.html' %}

{% block js %}

<script>
    function eliminarDepartamento(id_depa){
        Swal.fire({
            "tittle":"Estas Seguro?",
            "text":"Esta acción no se puede deshacer",
            "icon":"question",
            "showCancelButton":true,
            "cancelButtonText":"No, Cancelar",
            "confirmButtonText":"Si, Eliminar",
            "reverseButtons":true,
            "confirmButtonColor":"#dc3545"
        })
        .then(function(result) {
            if(result.isConfirmed) {
                window.location.href = "/eliminarDep/"+id_depa+"/"
            }
        })
    }
</script>

{% endblock %}

{% block contenido %}
{% load humanize %}
<br><br><br>
<div class="card">
    <div class="card-body">
        <h2>Listado de departamentos</h2>
        <hr>
        <table class="table table-striped table-hover table-responsive-sm">
            <tr>
                <th>Nombre</th>
                <th>Información</th>
                <th>entorno</th>
                <th>Servicios</th>
                <th>Tarifa</th>
                <th>Estado</th>
                <th>Opciones</th>
            </tr>
        
            {% for p in entity %}
        
            <tr>
                <td>{{ p.nombre | title }}</td>
                <td>{{ p.info_departamento }}</td>
                <td>{{ p.entorno_departamento }}</td>
                <td>{{ p.servicio_asociado }}</td>
                <td>{{ p.tarifa | intcomma }}</td>
                <td>
                    {% if p.estado  %}
                    Si
                    {% else %}
                    No
                    {% endif %}
                </td>
                <td>
                    {% if perms.app.change_departamento %}
                    <a href="{% url 'modificarDep' p.id_depa %}" class="btn btn-info btn-sm">Modificar</a>
                    {% endif %}

                    {% if perms.app.delete_departamento %}
                    <a href="#" onclick="eliminarDepartamento({{ p.id_depa }})" class="btn btn-danger btn-sm">Eliminar</a>
                    {% endif %}
                </td>
            </tr>
        
            {% endfor %}
        
        
        </table>
        <hr>
        <div>
            {% include 'app/paginator.html' %}
        </div>
    </div>
</div>



{% endblock %}

app/templates/deptos/modificar.html
{% extends 'app/base.html' %}

{% block contenido %}



<br><br>
        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-body">
                        <h2>Editar Departamentos</h2>
                        <hr>

                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form }}
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary">
                        &nbsp;
                        <input type="submit" value="Editar" class="btn btn-primary">   

                    </div>
                  

                </form>
                {{ mensaje }}

            </div>
        </div>


    </div>
</div>


{% endblock %}