app/urls.py
from django.urls import path, include
from .views import home, contacto, galeria, agregar_deptos, listarDeptos, modificarDeptos, eliminarDptos,\
    registro, DepartamentoViewset, reserva
from rest_framework import routers


router = routers.DefaultRouter()
router.register('depa', DepartamentoViewset)


urlpatterns = [
    path('', home, name="home"),
    path('contacto/', contacto, name="contacto"),
    path('galeria/', galeria, name="galeria"),
    path('agregarDep/', agregar_deptos, name="agregarDep"),
    path('listarDep/', listarDeptos, name="listarDep"),
    path('modificarDep/<id_depa>/', modificarDeptos, name="modificarDep"),
    path('eliminarDep/<id_depa>/', eliminarDptos, name="eliminarDep"),
    path('registro/', registro, name="registro"),
    path('api/', include(router.urls)),
     path('reserva/', reserva, name="reserva"),

]

webarriendos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.db.models.base import Model
from django.utils.regex_helper import Choice


class Acompaniante(models.Model):
    id_acomp = models.FloatField(primary_key=True)
    cantidad = models.BigIntegerField()
    direccion = models.CharField(max_length=150)
    telefono = models.CharField(max_length=20)
    correo = models.CharField(max_length=150)
    estado = models.FloatField()

    class Meta:
        managed = False
        db_table = 'acompaniante'


class Administrador(models.Model):
    id_admi = models.FloatField(primary_key=True)
    estado = models.FloatField()
    id_usua = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usua')

    class Meta:
        managed = False
        db_table = 'administrador'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128, blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150, blank=True, null=True)
    first_name = models.CharField(max_length=150, blank=True, null=True)
    last_name = models.CharField(max_length=150, blank=True, null=True)
    email = models.CharField(max_length=254, blank=True, null=True)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Cargo(models.Model):
    id_carg = models.FloatField(primary_key=True)
    nombre = models.CharField(max_length=150)
    detalle_cargo = models.CharField(max_length=200)
    estado = models.FloatField()

    class Meta:
        managed = False
        db_table = 'cargo'


class CheckIn(models.Model):
    id_chin = models.FloatField(primary_key=True)
    detalle_entrega = models.CharField(max_length=150)
    pago_pendiente = models.CharField(max_length=150)
    ingreso_conformidad = models.CharField(max_length=150)
    hora_chin = models.DateTimeField()
    fecha_chin = models.DateField()
    estado = models.FloatField()
    id_func = models.ForeignKey('Funcionario', models.DO_NOTHING, db_column='id_func')
    id_rese = models.ForeignKey('Reserva', models.DO_NOTHING, db_column='id_rese')

    class Meta:
        managed = False
        db_table = 'check_in'


class CheckOut(models.Model):
    id_chou = models.FloatField(primary_key=True)
    estado_entrega = models.CharField(max_length=50)
    multas_out = models.CharField(max_length=50)
    pagos_multas_out = models.CharField(max_length=50)
    hora_chou = models.DateTimeField()
    fecha_chou = models.DateField()
    estado = models.FloatField()
    id_func = models.ForeignKey('Funcionario', models.DO_NOTHING, db_column='id_func')
    id_chin = models.ForeignKey(CheckIn, models.DO_NOTHING, db_column='id_chin')

    class Meta:
        managed = False
        db_table = 'check_out'


class Cliente(models.Model):
    id_clie = models.FloatField(primary_key=True)
    estado = models.FloatField()
    id_acomp = models.ForeignKey(Acompaniante, models.DO_NOTHING, db_column='id_acomp')
    id_usua = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usua')

    class Meta:
        managed = False
        db_table = 'cliente'



class Comuna(models.Model):
    id_comu = models.FloatField(primary_key=True)
    nombre = models.CharField(max_length=150)
    estado = models.FloatField()
    id_prov = models.ForeignKey('Provincia', models.DO_NOTHING, db_column='id_prov')

    class Meta:
        managed = False
        db_table = 'comuna'
    
    
    def __str__(self):
        return self.nombre

class Conductor(models.Model):
    id_cond = models.FloatField(primary_key=True)
    nombre = models.CharField(max_length=150)
    apellido = models.CharField(max_length=150)
    direccion = models.CharField(max_length=150)
    correo = models.CharField(max_length=150)
    estado = models.FloatField()

    class Meta:
        managed = False
        db_table = 'conductor'


class Departamento(models.Model):
    id_depa = models.FloatField(primary_key=True)
    nombre = models.CharField(max_length=150)
    info_departamento = models.CharField(max_length=150)
    servicio_asociado = models.CharField(max_length=150)
    entorno_departamento = models.CharField(max_length=150)
    tarifa = models.BigIntegerField()
    condicion_uso = models.CharField(max_length=150)
    estado = models.FloatField()
    id_admi = models.ForeignKey(Administrador, models.DO_NOTHING, db_column='id_admi')
    id_edificio = models.ForeignKey('Edificio', models.DO_NOTHING, db_column='id_edificio')
    

    class Meta:
        managed = False
        db_table = 'departamento'


class Direccion(models.Model):
    id_dire = models.FloatField(primary_key=True)
    nombre_calle = models.CharField(max_length=150)
    numero_calle = models.IntegerField()
    estado = models.FloatField()
    id_comu = models.ForeignKey(Comuna, models.DO_NOTHING, db_column='id_comu')

    class Meta:
        managed = False
        db_table = 'direccion'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200, blank=True, null=True)
    action_flag = models.IntegerField()
    change_message = models.TextField(blank=True, null=True)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100, blank=True, null=True)
    model = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255, blank=True, null=True)
    name = models.CharField(max_length=255, blank=True, null=True)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField(blank=True, null=True)
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Edificio(models.Model):
    id_edificio = models.FloatField(primary_key=True)
    estado = models.FloatField()
    id_dire = models.ForeignKey(Direccion, models.DO_NOTHING, db_column='id_dire')

    class Meta:
        managed = False
        db_table = 'edificio'


class Funcionario(models.Model):
    id_func = models.FloatField(primary_key=True)
    estado = models.FloatField()
    id_carg = models.ForeignKey(Cargo, models.DO_NOTHING, db_column='id_carg')
    id_usua = models.ForeignKey('Usuario', models.DO_NOTHING, db_column='id_usua')

    class Meta:
        managed = False
        db_table = 'funcionario'


class InformeGanancia(models.Model):
    id_inga = models.FloatField(primary_key=True)
    ganancia_departamento = models.BigIntegerField()
    ganancia_zona = models.BigIntegerField()
    ganancia_diaria = models.BigIntegerField()
    ganancia_semanal = models.BigIntegerField()
    ganancia_anual = models.BigIntegerField()
    estado = models.FloatField()
    id_admi = models.ForeignKey(Administrador, models.DO_NOTHING, db_column='id_admi')

    class Meta:
        managed = False
        db_table = 'informe_ganancia'


class InformeReserva(models.Model):
    id_inre = models.FloatField(primary_key=True)
    detalle = models.CharField(max_length=150)
    estado = models.FloatField()

app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Turismo Real</title>
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,700;1,400;1,700&family=Open+Sans:ital,wght@0,400;0,700;1,600&display=swap" rel="stylesheet">
  
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% block css %}

    {% endblock %}
    <link rel="stylesheet" href="{% static 'app/css/estilos.css' %}">
    
</head>
<body>

    
    <header id="header">
        <img class="menu" src="{% static 'app/img/menuiconwhite.png' %}" alt="menu" id="menu">
        <div class="contenedor_logo">
            <img  class="logo"  src="{% static 'app/img/tecnomarketpngicono.png' %}" alt="logo">
        </div>

        <div>
            
            <nav id="nav">
                <ul>
                    <li>
                        <a href="{% url 'reserva' %}">Reserva</a>
                    </li>
                    <li>
                        <a href="{% url 'home' %}"> Inicio </a>
                    </li>
                    <li>
                        <a href="{% url 'contacto' %}">Contacto</a>
                    </li>
                    <li><a href="{% url 'galeria' %}">Galería</a></li>

                    {% if perms.app.add_departamento %}
                   <li><a href="{% url 'agregarDep' %}">Agregar Departamento</a></li>
                    {% endif %}

                    {% if perms.app.view_departamento %}
                   <li><a href="{% url 'listarDep' %}">Listar Departamentos</a></li>
                   {% endif %}

                   {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'logout' %}">Cerrar Sesión</a>
                    </li>
                    <li>
                        <a href="#">@{{ user.username }}</a>
                    </li>
                   {% else %}
                    <li>
                        <a href="{% url 'login' %}">Iniciar Sesión</a>
                    </li>
                    <li>
                        <a href="{% url 'registro' %}">Registrate</a>
                    </li>
                   {% endif %}

                </ul>
            </nav>

        </div>

    </header>

    <div id="contenido">

 

   {% block contenido %}
    
   {% endblock %}
    </div>


    <footer>
        <div class="marcas">
            <img src="{% static 'app/img/footer/apple.png' %}" alt="apple">
            <img src="{% static 'app/img/footer/lenovo.png' %}" alt="lenovo">
            <img src="{% static 'app/img/footer/microsoft.png' %}" alt="microsoft">
            <img src="{% static 'app/img/footer/samsung.png' %}" alt="samsung">
            <img src="{% static 'app/img/footer/xiaomi.png' %}" alt="xiaomi">
        </div>
        <div class="logo_footer">
            <img src="{% static 'app/img/tecnomarketpngicono.png' %}" alt="logo">
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    
    <script src="{% static 'app/js/menu.js' %}"></script>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% if messages %}
     {% for m in messages %}
        <script>
            Swal.fire({
                "title":"Feliciaciones",
                "text":"{{m}}",
                "icon":"success"
            })
        </script>
     {% endfor %}
    {% endif %}

{% block js %}

{% endblock %}



</body>
</html>

app/templates/app/contacto.html
{% extends 'app/base.html' %}

{% block contenido %}
<h2>Contactanos!</h2>
<form action="" class="formulario_contacto" id="formulario_contacto">
    <label for="nombre">Nombre</label>
    <input type="text" id="nombre" name="nombre">
    <br>
    <label for="email">Email</label>
    <input type="email" id="email" name="email" placeholder="tu@email.cl">
    <br>
    <label for="telefono">Telefono</label>
    <input type="number" name="telefono" id="telefono">
    <br>
    <label for="tipoconsulta">Tipo consulta</label>
    <select name="tipoconsulta" id="tipoconsulta">
        <option value="">seleccionar</option>
        <option value="consulta">consulta</option>
        <option value="reclamo">reclamo</option>
        <option value="sugerencia">sugerencia</option>
        <option value="felicitaciones">felicitaciones</option>
    </select>
    <br>
    <label for="mensaje">Mensaje</label>
    <textarea name="mensaje" id="mensaje" cols="30" rows="10"></textarea>
    <br>
    <input type="checkbox" name="avisos" id="avisos" checked>
    <label for="avisos">¿Desea recibir promociones/avisos a su email?</label>
    <br>
    <!--
    
    <label for="">Sexo</label>
    <label for="masculino">Masculino</label>
    <input type="radio" name="sexo" id="masculino" checked>
    <label for="femenino">Femenino</label>
    <input type="radio" name="sexo" id="femenino">

    <br>
    
    <label for="fechanacimiento">Fecha nacimiento</label>
    <input type="date" name="fechanacimiento" id="fechanacimiento">
    <br>
    <label for="color">Color</label>
    <input type="color" name="color" id="color">
    
    <br>
    <input type="datetime-local" name="" id="">-->

    <button type="button" id="btnEnviar" class="button">Enviar</button>
    

</form>

<table id="tablacontactos">
    
</table>
{% endblock %}

app/templates/app/galeria.html
{% extends 'app/base.html' %}
{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
{% endblock %}

{% block contenido %}
<h2>Galería de nuestra tienda</h2>
<br><br>
<div class="galeria">
     <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda1.jpg' %}"><img src="{% static 'app/img/tienda/tienda1.jpg' %}"></a>
     <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda2.jpeg' %}"><img src="{% static 'app/img/tienda/tienda2.jpeg' %}"></a>
     <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda3.jpg' %}"><img src="{% static 'app/img/tienda/tienda3.jpg' %}"></a>
     <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda4.jpg' %}"><img src="{% static 'app/img/tienda/tienda4.jpg' %}"></a>
     <a data-fancybox="gallery" href="{% static 'app/img/tienda/tienda5.jpg' %}"><img src="{% static 'app/img/tienda/tienda5.jpg' %}"></a>     
</div>

{% endblock %}

app/templates/app/home.html
{% extends 'app/base.html' %}

{% load static %}

{% block js %}
<script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>

<script>
    $(document).ready(function() {
      $('.slider').bxSlider({
          mode: 'fade',//horizontal, vertical, fade
          auto: true,
          pause: 2000
      });
    });
</script>
{% endblock %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
{% endblock %}

{% block contenido %}

{% load humanize %}


    
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="{% static 'app/img/depto5.jpg' %}" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'app/img/depto5.jpg' %}" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="{% static 'app/img/depto5.jpg' %}" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only"></span>
        </a>
      </div>
    
<div>
    <h2>Departamentos</h2>
    <hr>
   
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for p in departamentos %}
        <div class="col">
          <div class="card">
            <img src="{% static 'app/img/depto5.jpg' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5>{{ p.nombre | title}}</h5>
              <h2>{{ p.info_departamento }}</h2>
              <h3>{{ p.entorno_departamento }}</h3>
              <h3>${{ p.tarifa | intcomma }}</h3>
            </div>
          </div>
        </div>
        {% endfor %}
      
      
      </div>
     
</div>
{% endblock %}


<script>
  $('.carousel').carousel({
  interval: 2000
})
</script>

<!--      {% if p.imagen %}
    <div class="contenedor_productos">
        {% endif %}
        <img src="{{ p.imagen.url }}" alt="imagen departamentos"> -->

app/templates/app/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

app/templates/app/reserva.html
{% extends 'app/base.html' %}

{% block contenido %}
<h2>Reserva!</h2>
<form action="" class="formulario_contacto" method="post">
    
    {% csrf_token %}

    {{ form }}

    <br>
    <br>
    <button type="submit" id="btnEnviar" class="button">Enviar</button>
    

</form>

<table id="tablacontactos">
    
</table>
{% endblock %}